version: '3.1'
services:
  postgresql:
    image: postgres
    volumes:
      - ./backend/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=bookfinder
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
